#!/bin/sh
DIR=$(cd $(dirname $0);pwd)
ln -s -i $DIR/.zshrc $HOME
ln -s -i $DIR/.zsh $HOME
ln -s -i $DIR/.screenrc $HOME
ln -s -i $DIR/.tmux.conf $HOME
ln -s -i $DIR/.autotest $HOME
ln -s -i $DIR/.irbrc $HOME
cp $DIR/.rails_ok.png $HOME
cp $DIR/.rails_fail.png $HOME
