[terminal.shell]
program = "wsl.exe"
args = ["-d", "Ubuntu"]

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
bold = { family = "UDEV Gothic NF", style = "Bold" }
italic = { family = "UDEV Gothic NF", style = "Italic" }
