export PATH="$HOME/.local/bin:$PATH"

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

zinit light zsh-users/zsh-completions
zinit light zdharma-continuum/fast-syntax-highlighting
zinit light marlonrichert/zsh-autocomplete
zinit load agkozak/zsh-z

eval "$(starship init zsh)"
. "$HOME/.atuin/bin/env"

# Atuinの自動バインドを無効化し、Ctrl-rだけAtuinに割り当てる
export ATUIN_NOBIND="1"
eval "$(atuin init zsh)"
bindkey '^R' atuin-search

# set up ls aliases with color support
if ls --color=auto . >/dev/null 2>&1; then
  alias ls='ls --color=auto'
  alias la='ls --color=auto -a'
  alias ll='ls --color=auto -l -h'
  alias lal='ls --color=auto -a -l -h'
else
  alias ls='ls -G'
  alias la='ls -G -a'
  alias ll='ls -G -l -h'
  alias lal='ls -G -a -l -h'
fi

# Define a custom `cd` function that lists the contents of the directory after changing into it
function cd() {
  builtin cd "$@" || return
  # OSによってlsのオプションを切り替え
  if ls --color=auto . &>/dev/null; then
    ls -lh --color=auto
  else
    ls -lh -G
  fi
}

# exec ls if the buffer is empty
# This function will execute `ls` if the command line is empty when you press Enter.
function accept-line-or-ls() {
  if [[ -z $BUFFER ]]; then
    ls
    echo
    zle reset-prompt
  else
    zle accept-line
  fi
}
zle -N accept-line-or-ls
bindkey '^M' accept-line-or-ls
